[theme]
#name = "solarized-dark"
name = "slick"
[theme.overrides]
idle_bg = "#585858"
idle_fg = "#f8f8f2"

[icons]
name = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 2
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "temperature"

[[block]]
block = "battery"

[[block]]
block = "time"
interval = 60
format = "%a %Y/%m/%d %H:%M:%S"
